config/routes.rb
    get '/avales-candidaturas-barcelona', to: 'page#avales_barcelona', as: 'avales_barcelona'
    get '/primarias-andalucia', to: 'page#primarias_andalucia', as: 'primarias_andalucia'
    get '/listas-primarias-andaluzas', to: 'page#listas_primarias_andaluzas', as: 'listas_primarias_andaluzas'

    get '/responsables-organizacion-municipales', to: 'page#responsables_organizacion_municipales', as: 'responsables_organizacion_municipales'
    get '/responsables-municipales-andalucia', to: 'page#responsables_municipales_andalucia', as:'responsables_municipales_andalucia'
    get '/plaza-podemos-municipal', to: 'page#plaza_podemos_municipal', as:'plaza_podemos_municipal'
    get '/portal-transparencia-cc-estatal', to: 'page#portal_transparencia_cc_estatal', as:'portal_transparencia_cc_estatal'
    get '/mujer-igualdad', to: 'page#mujer_igualdad', as:"mujer_igualdad"
    get '/solicitud-consulta-ciudadana-candidatura-unidad-popular', to: 'page#alta_consulta_ciudadana', as:"alta_consulta_ciudadana"
    get '/representantes-electorales-extranjeros', to: 'page#representantes_electorales_extranjeros', as:"representantes_electorales_extranjeros"
    get '/responsables-areas-cc-autonomicos', to: 'page#responsables_areas_cc_autonomicos', as:"responsables_areas_cc_autonomicos"
    get '/boletin-correo-electronico', to: 'page#boletin_correo_electronico', as:"boletin_correo_electronico"
    get '/responsable-web-autonomico', to: 'page#responsable_web_autonomico', as: 'responsable_web_autonomico'

    get '/comparte-el-cambio/compartir-casa', to: 'page#offer_hospitality', as: 'offer_hospitality'
    get '/comparte-el-cambio/encuentra-casa', to: 'page#find_hospitality', as: 'find_hospitality'
    get '/comparte-el-cambio/compartir-coche-sevilla', to: 'page#share_car_sevilla', as: 'share_car_sevilla'
    get '/comparte-el-cambio/encuentra-viaje-sevilla', to: 'page#find_car_sevilla', as: 'find_car_sevilla'
    get '/comparte-el-cambio/compartir-coche-doshermanas', to: 'page#share_car_doshermanas', as: 'share_car_doshermanas'
    get '/comparte-el-cambio/encuentra-viaje-doshermanas', to: 'page#find_car_doshermanas', as: 'find_car_doshermanas'
    get '/comparte-el-cambio/valoracion-propietarios', to: 'page#comparte_cambio_valoracion_propietarios', as: 'comparte_cambio_valoracion_propietarios'
    get '/comparte-el-cambio/valoracion-usuarios', to: 'page#comparte_cambio_valoracion_usuarios', as: 'comparte_cambio_valoracion_usuarios'

    get '/apoderados-campana-autonomica-andalucia', to: 'page#apoderados_campana_autonomica_andalucia', as: 'apoderados_campana_autonomica_andalucia'
    get '/candidaturas-primarias-autonomicas', to: 'page#candidaturas_primarias_autonomicas', as: 'candidaturas_primarias_autonomicas'
    get '/listas-primarias-autonomicas', to: 'page#listas_primarias_autonomicas', as: 'listas_primarias_autonomicas'
    get '/avales-candidaturas-primarias', to: 'page#avales_candidaturas_primarias', as: 'avales_candidaturas_primarias'
    get '/iniciativa-ciudadana', to: 'page#iniciativa_ciudadana', as: 'iniciativa_ciudadana'

    get '/cuentas-consejos-autonomicos-33', to: 'page#cuentas_consejos_autonomicos', as: 'cuentas_consejos_autonomicos'
    get '/condiciones-uso-correo-34', to: 'page#condiciones_uso_correo', as: 'condiciones_uso_correo'

    get '/propuestas', to: 'proposals#index', as: 'proposals'
    get '/propuestas/info', to: 'proposals#info', as: 'proposals_info'
    get '/propuestas/:id', to: 'proposals#show', as: 'proposal'
    post '/apoyar/:proposal_id', to: 'supports#create', as: 'proposal_supports'

    get :notices, to: 'notice#index', as: 'notices'
    get '/vote/create/:election_id', to: 'vote#create', as: :create_vote
    get '/vote/create_token/:election_id', to: 'vote#create_token', as: :create_token_vote
    get '/vote/check/:election_id', to: 'vote#check', as: :check_vote

    get '/vote/sms_check/:election_id', to: 'vote#sms_check', as: :sms_check_vote
    get '/vote/send_sms_check/:election_id', to: 'vote#send_sms_check', as: :send_sms_check_vote

    get '/votos/:election_id/:token', to: 'vote#election_votes_count', as: 'election_votes_count'
    get '/votos/:election_id/:election_location_id/:token', to: 'vote#election_location_votes_count', as: 'election_location_votes_count'
    match '/paper_vote/:election_id/:election_location_id/:token', to: 'vote#paper_vote', as: 'election_location_paper_vote', via: %w(get post)

    devise_for :users, controllers: {
      registrations: 'registrations',
      passwords:     'passwords',
      confirmations: 'confirmations',
      sessions:      'sessions'
    }

    get '/financiacion', to: 'page#funding', as: 'funding'
    get '/microcreditos', to: 'microcredit#index', as: 'microcredit'
    get '/microcréditos', to: redirect('/microcreditos')
    get '/microcreditos/provincias', to: 'microcredit#provinces'
    get '/microcreditos/municipios', to: 'microcredit#towns'
    get '/microcreditos/informacion', to: 'microcredit#info', as: 'microcredits_info'
    get '/microcreditos/informacion/papeletas_con_futuro', to: 'microcredit#info_mailing', as: 'microcredits_info_mailing'
    get '/microcreditos/informacion/euskera', to: 'microcredit#info_euskera', as: 'microcredits_info_euskera'
    get '/microcreditos/renovar(/:loan_id/:hash)', to: 'microcredit#renewal', as: :renewal_microcredit_loan
    get '/microcreditos/:id', to: 'microcredit#new_loan', as: :new_microcredit_loan
    get '/microcreditos/:id/detalle', to: 'microcredit#show_options', as: :show_microcredit_options_detail
    get '/microcreditos/:id/login', to: 'microcredit#login', as: :microcredit_login
    post '/microcreditos/:id', to: 'microcredit#create_loan', as: :create_microcredit_loan
    get '/microcreditos/:id/renovar(/:loan_id/:hash)', to: 'microcredit#loans_renewal', as: :loans_renewal_microcredit_loan
    post '/microcreditos/:id/renovar/:loan_id/:hash', to: 'microcredit#loans_renew', as: :loans_renew_microcredit_loan

    authenticate :user do
      scope :validator do
        scope :sms do
          get :step1, to: 'sms_validator#step1', as: 'sms_validator_step1'
          get :step2, to: 'sms_validator#step2', as: 'sms_validator_step2'
          get :step3, to: 'sms_validator#step3', as: 'sms_validator_step3'
          post :phone, to: 'sms_validator#phone', as: 'sms_validator_phone'
          post :captcha, to: 'sms_validator#captcha', as: 'sms_validator_captcha'
          post :valid, to: 'sms_validator#valid', as: 'sms_validator_valid'
        end
      end

      scope :colabora do
        delete 'baja', to: 'collaborations#destroy', as: 'destroy_collaboration'
        get 'ver', to: 'collaborations#edit', as: 'edit_collaboration'
        get '', to: 'collaborations#new', as: 'new_collaboration'
        get 'confirmar', to: 'collaborations#confirm', as: 'confirm_collaboration'
        post 'crear', to: 'collaborations#create', as: 'create_collaboration'
        post 'modificar', to: 'collaborations#modify', as: 'modify_collaboration'
        get 'puntual', to: 'collaborations#single', as: 'single_collaboration'
        get 'OK', to: 'collaborations#OK', as: 'ok_collaboration'
        get 'KO', to: 'collaborations#KO', as: 'ko_collaboration'
      end

      get 'verificacion-identidad(/:election_id)', to: 'user_verifications#new', as: 'new_user_verification'
      post 'verificacion-identidad(/:election_id)', to: 'user_verifications#create', as: 'create_user_verification'
      get 'report/(:report_code)', to: 'user_verifications#report', as: 'report_user_verification'
      get 'report_exterior/(:report_code)', to: 'user_verifications#report_exterior', as: 'report_exterior_user_verification'
      get 'report_town/(:report_code)', to: 'user_verifications#report_town', as: 'report_town_user_verification'
    end

    scope :impulsa do
      get '', to: 'impulsa#index', as: 'impulsa'
      get 'proyecto', to: 'impulsa#project', as: 'project_impulsa'
      get 'proyecto/:step', to: 'impulsa#project_step', as: 'project_step_impulsa'
      get 'evaluacion', to: 'impulsa#evaluation', as: 'evaluation_impulsa'
      post 'revisar', to: 'impulsa#review', as: 'review_impulsa'
      delete 'proyecto/borrar', to: 'impulsa#delete', as: 'delete_impulsa'
      post 'modificar', to: 'impulsa#update', as: 'update_impulsa'
      post 'modificar/:step', to: 'impulsa#update_step', as: 'update_step_impulsa'
      post 'subir/:step/:field', to: 'impulsa#upload', as: 'upload_impulsa', constraints: { field: /[^\/]*/ }
      delete 'borrar/:step/:field', to: 'impulsa#delete_file', as: 'delete_file_impulsa', constraints: { field: /[^\/]*/ }
      get 'descargar/:field', to: 'impulsa#download', as: 'download_impulsa', constraints: { field: /[^\/]*/ }

    end

    scope :brujula do
      get '', to: 'blog#index', as: 'blog'
      get ':id', to: 'blog#post', as: 'post'
      get 'categoria/:id', to: 'blog#category', as: 'category'
    end

    # http://stackoverflow.com/a/8884605/319241
    devise_scope :user do
      get '/registrations/regions/provinces', to: 'registrations#regions_provinces'
      get '/registrations/regions/municipies', to: 'registrations#regions_municipies'
      get '/registrations/vote/municipies', to: 'registrations#vote_municipies'

      authenticated :user do
        root to: 'tools#index', as: :authenticated_root
        get '/tools/militant_request', to: 'tools#militant_request', as: 'tools_militant_request'
        get 'password/new', to: 'legacy_password#new', as: 'new_legacy_password'
        post 'password/update', to: 'legacy_password#update', as: 'update_legacy_password'
        delete 'password/recover', to: 'registrations#recover_and_logout'
      end
      unauthenticated do
        root to: 'sessions#new', as: :root
      end
    end

    %w(404 422 500).each do |code|
      get code, to: 'errors#show', code: code
    end

    DynamicRouter.load
  end
  # /admin
  ActiveAdmin.routes(self)

  constraints CanAccessResque.new do

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :authenticate_user!
  before_action :user_elections
  before_action :get_promoted_forms

  def index
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def user_elections
    @all_elections = Election.upcoming_finished.map { |e| e if e.has_valid_location_for?(current_user, check_created_at: false) } .compact

    @elections = @all_elections.select { |e| e.is_active? }
    @upcoming_elections = @all_elections.select { |e| e.is_upcoming? }
    @finished_elections = @all_elections.select { |e| e.recently_finished? }
  end

  def get_promoted_forms
    @promoted_forms = Page.where(promoted: true).order(priority: :desc)
  end
end

app/views/tools/_demo.html.erb
<% content_for :title, "Forma parte del cambio en Andalucía" %>

<section class="tools">
<%= link_to image_tag("banner_collabs.png", alt: "colabora.podemos.info", style: 'max-width:100%'), new_collaboration_path %>
</section>

<%= content_tag(:h2, "Forma parte del cambio en Andalucía") %>
<section class="tools">
<ul>
  <li class="box-tool">
  <div class="box-tool">
    <h3>Comparte viaje a Sevilla</h3>
    <div class="tool-text">
      <p>Si vas en coche a Sevilla y te sobran plazas, anúncialo y otras personas podrán ponerse en contacto contigo para compartir el viaje y los gastos del mismo. </p>
    </div><!--.tool-text-->
    <div class="buttonbox">
      <%= link_to "Comparte tu coche", share_car_sevilla_path, class: "button" %>
      <%= link_to "Encuentra coche", find_car_sevilla_path, class: "button" %>
    </div>
  </div><!--.box-tool-->
  </li>
  <li class="box-tool">
  <div class="box-tool">
    <h3>Comparte viaje a Dos Hermanas</h3>
    <div class="tool-text">
      <p>Si vas en coche a Dos Hermanas y te sobran plazas, anúncialo y otras personas podrán ponerse en contacto contigo para compartir el viaje y los gastos del mismo. </p>
    </div><!--.tool-text-->
    <div class="buttonbox">
      <%= link_to "Comparte tu coche", share_car_doshermanas_path, class: "button" %>
      <%= link_to "Encuentra coche", find_car_doshermanas_path, class: "button" %>
    </div>
  </div><!--.box-tool-->
  </li>
  <li class="box-tool">
  <div class="box-tool">
    <h3>Comparte casa</h3>
    <div class="tool-text">
      <p>Si tienes sitio en tu casa en Sevilla, compártelo y haz posible que otras personas puedan participar en el cambio en Andalucía.</p>
    </div><!--.tool-text-->
    <div class="buttonbox">
      <%= link_to "Comparte tu casa", offer_hospitality_path, class: "button" %>
      <%= link_to "Encuentra alojamiento", find_hospitality_path, class: "button" %>
    </div><!--.buttonbox-->
  </div><!--.box-tool-->
  </li>
  <li class="box-tool">
  <div class="box-tool">
    <h3>La expresión del cambio en Andalucía</h3>
    <div class="tool-text">
      <p>Comparte tus creaciones por el cambio en Andalucía. También puedes participar en el concurso de carteles para el 20M.</p>
    </div><!--.tool-text-->
    <div class="buttonbox">
      <a href="https://laexpresiondelcambio.info" class="button">COMPARTE TUS CREACIONES</a>
    </div><!--.buttonbox-->
  </div><!--.box-tool-->
  </li>
</ul>
</section>

app/views/tools/_election.html.erb
<% if election.user_created_at_max %>
<p class="sub-h3">Recuerda que para participar en la votación debes haberte inscrito en este portal antes del <%= l election.user_created_at_max, format: "%-d de %B de %Y a las %H:%M" %></p>
<% end %>
<p class="sub-h3">
<% if !election.paper? && current_user.can_change_vote_location? and election.multiple_territories?%>
Accederás a la votación de<% case election.scope
     when 1 %> la comunidad autónoma en la
  <% when 2 %> la provincia en la
  <% when 3 %>l municipio en el
  <% when 4 %> la isla en la
  <% end %> que <% if election.user_created_at_max %>estabas inscrito/a en el momento del cierre del censo.<% else %>estás inscrito/a. Puedes actualizar tu ubicación, pero recuerda que sólo tu último voto es válido.<% end %>
<% end %>
</p>

<div class="box-poll">
  <div>
    <p class="poll-q"><%= election.full_title_for current_user %></p>
    <p class="date"><%= l election.starts_at, format: :short %> - <%= l election.ends_at, format: :short %></p>
  </div>
  <% if election.has_valid_location_for?(current_user) && election.has_valid_user_created_at?(current_user) %>
    <% if election.paper? %>
      <%= link_to election.info_url, class: 'button button-vote' do %>
        <span><%= election.info_text %></span>
      <% end %>
    <% elsif election.nvotes? %>
      <%= link_to create_vote_path(election_id: election.id), class: 'button button-vote' do %>
        <% if current_user.has_already_voted_in election.id %>
          <span>Cambiar el voto</span>
        <% else %>
          <span>Votar</span>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to election.external_link, class: 'button button-vote' do %>
        <span>Votar</span>
      <% end %>
    <% end %>
  <% else %>
    <span class="button button-danger"><span>Censo cerrado</span></span>
  <% end %>
</div>

app/views/tools/_election_finished.html.erb
<div class="box">
  <div class="box-vote">
    <h3><strong>Las votaciones de <%= election.title %> ya han cerrado.</strong></h3>
    <p class="sub-h3"> <%= raw election.close_message %></p>
  </div>
</div>

app/views/tools/_election_upcoming.html.erb
<div class="box">
  <div class="box-vote">
    <h3><strong>Las votaciones de <%= election.title %> están a punto de empezar.</strong></h3>
    <p class="sub-h3">Las urnas se abrirán el <%= l election.starts_at, format: "%-d de %B de %Y a las %H:%M" %>.</p>
  </div>
</div>

app/views/tools/_elections.html.erb
<div class="box">
  <div class="box-vote">
    <% if !current_user.has_vote_town? %>
      <p><strong>Por favor, indica tu lugar de participación en tu perfil.</strong></p>
    <% end %>
    <h3><strong>Hay <% if @elections.length==1%>una votación<%else%>votaciones<%end%> en curso. ¡Participa!</strong></h3>
    <% if @elections.any? {|el| el.nvotes? } %>
      <p class="sub-h3"><% if @elections.length==1%>La votación utiliza<%else%>Las votaciones utilizan<%end%> el sistema seguro de <a href="https://nvotes.org" target="_blank"><b>nVotes</b></a>.</p>
    <% end %>
    <% @elections.each do |election| %>
      <%= render partial: "election", locals: { election: election } %>
    <% end %>
  </div>
</div>

app/views/tools/_last_election.html.erb
<div class="box">
  <div class="box-vote">
    <h3><strong>Las votaciones de <%= election.title %> ya han cerrado.</strong></h3>
    <p class="sub-h3"> <%= raw election.close_message %></p>
  </div>
</div>

app/views/tools/_microcredit_renewal.html.erb
<div class="box">
  <div class="box-vote">
    <div class="box-poll">
      <div>
        <p class="poll-q">Tienes microcréditos que puedes renovar</p>
      </div>

          <%= link_to renewal_microcredit_loan_path, class: 'button button-vote' do %>
            <span><%= t("microcredit.loans_renewal.renew_button") %></span>
          <% end %>
    </div>
  </div>
</div>

app/views/tools/_no_elections.html.erb
<div class="box">
  <div class="box-vote">
    <h3><strong><%= t("podemos.no_election.header") %></strong></h3>
    <p class="sub-h3"> <%= t("podemos.no_election.message") %></p>
  </div>
</div>

app/views/tools/_other_tools.html.erb
<% if current_user.any_microcredit_renewable? %>
<%=render partial: "microcredit_renewal" %>
<%end%>
<section class="tools">
  <ul>

    <% if current_user.militant? %>
      <li class="box-tool-large">
        <div class="box-tool-large">
          <h3>¡Ya eres militante!</h3>
          <div class="tool-text" style="padding-bottom: 1em;">
            <p>Pulsa aquí para conocer tus derechos en detalle</p>

          </div><!--.tool-text-->

          <div class="buttonbox">
            <%= link_to "Conocer los detalles", tools_militant_request_path, class: "button" %>
          </div>
        </div><!--.box-tool-->
      </li>
    <% else %>
      <li class="box-tool-large">
        <div class="box-tool-large">
          <h3>Todavía no eres Militante</h3>
          <div class="tool-text" style="padding-bottom: 1em;">
            <p>Si lo deseas, además de estar inscrit<% if (current_user.gender == 'M')%>o<% elsif current_user.gender == 'F'%>a<% else %>o/a<%end%> en Podemos, puedes darte de alta en el nuevo Censo de Militantes.</p>

          </div><!--.tool-text-->

          <div class="buttonbox">
            <%= link_to "Apúntate aquí", tools_militant_request_path, class: "button" %>
          </div>
        </div><!--.box-tool-->
      </li>
    <%end%>
  </ul>
</section><!--.tools-->
<%= render partial: "promoted_forms" %>

app/views/tools/_promoted_forms.html.erb
<section class="tools">
  <ul>
    <% @promoted_forms.each do |f| %>
      <li class="box-tool-large">
        <div class="box-tool-large">
          <h3><%=f.title %></h3>

          <div class="tool-text" style="padding-bottom: 1em;">
            <p><%=f.meta_description %></p>
          </div>

          <div class="buttonbox">
            <%= link_to "#{f.text_button.strip.empty? ? "Apúntate aquí" : f.text_button}", "/#{f.slug}", class: "button" %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</section>

app/views/tools/_unused_tools.html.erb
<section class="tools">
  <ul>
    <% user_verification = UserVerification.where(user_id: current_user.id) %>
    <% if (current_user && current_user.has_future_verified_elections? && (!current_user.verified || user_verification.none? || (user_verification && !user_verification.accepted))) %>
      <li class="box-tool-large">
        <div class="box-tool-large">
          <h3>VERIFÍCATE AQUÍ</h3>
          <div class="tool-text" style="padding-bottom: 1em;">
            <p>Recuerda que para tomar parte en las votaciones de Podemos antes tienes que haber verificado tu identidad.
              <br/>Puedes hacerlo ahora, solo te llevará 2 minutos. ¿A qué esperas? ¡Identifícate con Podemos y participa!</p>

          </div><!--.tool-text-->

          <div class="buttonbox">
            <%= link_to "Verifícate aquí", new_user_verification_path, class: "button" %>
          </div>
        </div><!--.box-tool-->
      </li>
    <%end%>
    <!--li class="box-tool-large">
      <div class="box-tool-large">
        <h3>CENSO DE MILITANTES</h3>
        <div class="tool-text" style="padding-bottom: 1em;">
            <p>Si además de ser simpatizante militas en algún espacio de Podemos, regístrate aquí.
            <br/> Para más información dirígete a la Secretaría de Organización de tu comunidad autónoma.</p>

        </div--><!--.tool-text-->

    <!--div class="buttonbox">
        < %= link_to "Regístrate aquí", "https://participa.podemos.info/registro-censo-militantes", class: "button" %>
    </div>
  </div--><!--.box-tool-->
    <!--/li-->
  </ul>
</section><!--.tools-->

app/views/tools/_verification_pending.html.erb
<div class="col-b-4a12">
  <div class="verif-new-first">
    <p class="title"><%= t('verification.pending0_html') %></p>
    <p><%= t('verification.pending1_html') %></p>

    <div class="verif-new-docu">
      <span><%= image_tag "ico.verif.dni.png" %></span>
      <span class="verif-docu-txt"><%= t('verification.pending2_html') %></span>
    </div>
  </div>
</div>

<div class="col-b-4a12">
  <div class="verif-new-second">
    <p class="title"><%= t('verification.pending3_html') %></p>

    <div class="verif-left">
      <span class="verif-item verif-img-1"><%= image_tag "ico.verif.passport.png" %></span>
      <ul class="verif-item">
        <%= t('verification.pending4_html') %>
      </ul>
    </div>

    <span class="verif-new-or">
        <%= t('verification.pending5_html') %>
    </span>

    <div class="verif-right">
      <ul class="verif-item">
        <%= t('verification.pending6_html') %>
      </ul>
      <span class="verif-item verif-img-2"><%= image_tag "ico.verif.doc.png" %></span>
    </div>

    </div>
  </div>
</div>

<div class="col-b-4a12">
  <div class="verif-new-third">

    <p class="title"> <%= t('verification.pending8_html') %> </p>
    <p class="title"> <%= t('verification.pending7_html') %> </p>
    <%= render partial: "verification/map", locals: {centers: @centers} %>
  </div>
</div>

app/views/tools/index.html.erb
<div class="content-content cols">
  <div class="row">
    <div class="col-b-4a12">
      <% content_for :title, "Herramientas de participación ciudadana" %>
      <%= content_tag(:h2, "Herramientas de participación ciudadana") %>
      <% if @elections.count > 0 %>
        <%= render partial: 'elections' %>
      <% else %>
        <% if @upcoming_elections.count > 0 %>
          <%= render partial: 'election_upcoming', locals: { election: @upcoming_elections[-1] } %>
        <% elsif @finished_elections.count > 0 %>
          <%= render partial: 'election_finished', locals: { election: @finished_elections[-1] } %>
        <!--% elsif Rails.env.development? %-->
          <!-- %= render partial: "other_tools" % -->
        <% elsif Date.today < Date.civil(2015,03,20) %>
          <%= render partial: 'demo' %>
        <% else %>
          <%= render partial: 'no_elections' %>
        <% end %>
        <%= render partial: "other_tools" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tools/militant_request.html.erb
<% content_for :title, "Militancia" %>
<div class="content-content cols">
  <div class="row">
    <div class="col-b-4a12">
      <% if current_user.militant? %>
        <h2>¡Hola, <%= current_user.first_name %>!</h2>
        <h3></h3>
        <p>Ya eres militante de Podemos. Para garantizar tu participación a todos los niveles, comprueba la activación de tu Círculo (consulta cualquier duda a tu Secretaría de Organización Autonómica o a la Secretaría de Círculos). En los próximos meses, facilitaremos la forma de identificación para que puedas participar en tu Círculo.</p>
        <p>Como militante, según los documentos de la Tercera Asamblea Ciudadana de Podemos, tienes los siguientes derechos:</p>
        <%= raw t('militant.features') %>
        <p>Un partido no es nada sin sus militantes. Gracias por apoyar Podemos.</p>
      <% else %>
        <h2>¡Hola, <%= current_user.first_name %>!</h2>
          <p>Si lo deseas, además de estar inscrit<% if (current_user.gender == 'M')%>o<% elsif current_user.gender == 'F'%>a<% else %>o/a<%end%> en Podemos, puedes darte de alta en el nuevo censo de militantes. Los y las militantes de Podemos, siempre según los nuevos documentos y a través de su Círculo activo, son ahora protagonistas exclusivos a la hora de:</p>
          <%= raw t('militant.features') %>

          <h3>Para ser militante de Podemos debes cumplir tres condiciones:</h3>
          <p>1.- Verificar tu inscripción en Podemos. Si aún no lo has hecho, puedes hacer clic <%= link_to "aquí", new_user_verification_path %> y seguir los pasos necesarios para verificar tu identidad.</p>
          <%if current_user.verified? %>
            <p class="text-green">Ya cumples con esta condición <%= fa_icon("check-circle") %></p>
          <%elsif current_user.user_verifications.last.status == "pending"%>
            <p class="text-purple">Verificación en proceso de revisión...<%= fa_icon("hourglass") %> </p>
          <% else %>
            <p class="text-orange">No cumples con esta condición <%= fa_icon("times-circle") %></p>
          <% end %>

        <p> 2.- Adscribir tu participación en Podemos como militante a un Círculo concreto. Para ello puedes hacer clic en tus <%= link_to "Datos personales", edit_user_registration_path %> y seleccionar el Círculo en el que militas en el campo correspondiente. Tu Círculo deberá tener el estatus de activo para participar en los distintos procesos que se organicen. Si has marcado que tu Círculo no está activo o está en construcción, por favor indícanos en <a href="https://participa.podemos.info/solicitud-activacion-circulo">este formulario</a> de qué Círculo se trata. </p>
          <% if current_user.in_circle? %>
              <p class="text-green">Ya cumples con esta condición <%= fa_icon("check-circle") %></p>
          <% else %>
              <p class="text-orange">No cumples con esta condición <%= fa_icon("times-circle") %></p>
          <% end %>

          <p> 3.- Contribuir al sostenimiento de Podemos con el pago de una cuota popular de militante de al menos 3 € al mes. Si puedes pagar dicha cuota, haz clic <%= link_to "aquí", new_collaboration_path %> o en la sección "Colabora" del menú superior, y rellena los campos para establecer una colaboración periódica.</p>
          <p>Si debido a tu situación personal te encuentras dentro de alguno de los supuestos de exención voluntaria del pago de la cuota, por favor, rellena <a href='https://participa.podemos.info/solicitud-exencion-cuota-militancia'>este formulario</a> en el que te facilitamos un modelo de declaración jurada al respecto para que lo completes.</p>
          <%if current_user.has_min_monthly_collaboration? %>
              <p class="text-green">Ya cumples con esta condición <%= fa_icon("check-circle") %></p>
          <% elsif current_user.collaborations.where.not(frequency:0).where(status:[0,2]).exists?%>
              <p class="text-purple">Colaboración activa. Esperando el pago de la primera cuota... <%= fa_icon("hourglass") %> </p>
          <%elsif current_user.exempt_from_payment? %>
              <p class="text-purple">Estás exento de pagar la cuota <%= fa_icon("check-circle") %>)</p>
          <% else %>
              <p class="text-orange">No cumples con esta condición <%= fa_icon("times-circle") %></p>
          <% end %>
        <p>Si necesitas ayuda, escribe un correo electrónico a <a href="mailto:soportemilitantes@podemos.info">soportemilitantes@podemos.info</a>.</p>
      <% end %>
    </div>
  </div>
</div>