config/routes.rb
    get '/avales-candidaturas-barcelona', to: 'page#avales_barcelona', as: 'avales_barcelona'
    get '/primarias-andalucia', to: 'page#primarias_andalucia', as: 'primarias_andalucia'
    get '/listas-primarias-andaluzas', to: 'page#listas_primarias_andaluzas', as: 'listas_primarias_andaluzas'

    get '/responsables-organizacion-municipales', to: 'page#responsables_organizacion_municipales', as: 'responsables_organizacion_municipales'
    get '/responsables-municipales-andalucia', to: 'page#responsables_municipales_andalucia', as:'responsables_municipales_andalucia'
    get '/plaza-podemos-municipal', to: 'page#plaza_podemos_municipal', as:'plaza_podemos_municipal'
    get '/portal-transparencia-cc-estatal', to: 'page#portal_transparencia_cc_estatal', as:'portal_transparencia_cc_estatal'
    get '/mujer-igualdad', to: 'page#mujer_igualdad', as:"mujer_igualdad"
    get '/solicitud-consulta-ciudadana-candidatura-unidad-popular', to: 'page#alta_consulta_ciudadana', as:"alta_consulta_ciudadana"
    get '/representantes-electorales-extranjeros', to: 'page#representantes_electorales_extranjeros', as:"representantes_electorales_extranjeros"
    get '/responsables-areas-cc-autonomicos', to: 'page#responsables_areas_cc_autonomicos', as:"responsables_areas_cc_autonomicos"
    get '/boletin-correo-electronico', to: 'page#boletin_correo_electronico', as:"boletin_correo_electronico"
    get '/responsable-web-autonomico', to: 'page#responsable_web_autonomico', as: 'responsable_web_autonomico'

    get '/comparte-el-cambio/compartir-casa', to: 'page#offer_hospitality', as: 'offer_hospitality'
    get '/comparte-el-cambio/encuentra-casa', to: 'page#find_hospitality', as: 'find_hospitality'
    get '/comparte-el-cambio/compartir-coche-sevilla', to: 'page#share_car_sevilla', as: 'share_car_sevilla'
    get '/comparte-el-cambio/encuentra-viaje-sevilla', to: 'page#find_car_sevilla', as: 'find_car_sevilla'
    get '/comparte-el-cambio/compartir-coche-doshermanas', to: 'page#share_car_doshermanas', as: 'share_car_doshermanas'
    get '/comparte-el-cambio/encuentra-viaje-doshermanas', to: 'page#find_car_doshermanas', as: 'find_car_doshermanas'
    get '/comparte-el-cambio/valoracion-propietarios', to: 'page#comparte_cambio_valoracion_propietarios', as: 'comparte_cambio_valoracion_propietarios'
    get '/comparte-el-cambio/valoracion-usuarios', to: 'page#comparte_cambio_valoracion_usuarios', as: 'comparte_cambio_valoracion_usuarios'

    get '/apoderados-campana-autonomica-andalucia', to: 'page#apoderados_campana_autonomica_andalucia', as: 'apoderados_campana_autonomica_andalucia'
    get '/candidaturas-primarias-autonomicas', to: 'page#candidaturas_primarias_autonomicas', as: 'candidaturas_primarias_autonomicas'
    get '/listas-primarias-autonomicas', to: 'page#listas_primarias_autonomicas', as: 'listas_primarias_autonomicas'
    get '/avales-candidaturas-primarias', to: 'page#avales_candidaturas_primarias', as: 'avales_candidaturas_primarias'
    get '/iniciativa-ciudadana', to: 'page#iniciativa_ciudadana', as: 'iniciativa_ciudadana'

    get '/cuentas-consejos-autonomicos-33', to: 'page#cuentas_consejos_autonomicos', as: 'cuentas_consejos_autonomicos'
    get '/condiciones-uso-correo-34', to: 'page#condiciones_uso_correo', as: 'condiciones_uso_correo'

    get '/propuestas', to: 'proposals#index', as: 'proposals'
    get '/propuestas/info', to: 'proposals#info', as: 'proposals_info'
    get '/propuestas/:id', to: 'proposals#show', as: 'proposal'
    post '/apoyar/:proposal_id', to: 'supports#create', as: 'proposal_supports'

    get :notices, to: 'notice#index', as: 'notices'
    get '/vote/create/:election_id', to: 'vote#create', as: :create_vote
    get '/vote/create_token/:election_id', to: 'vote#create_token', as: :create_token_vote
    get '/vote/check/:election_id', to: 'vote#check', as: :check_vote

    get '/vote/sms_check/:election_id', to: 'vote#sms_check', as: :sms_check_vote
    get '/vote/send_sms_check/:election_id', to: 'vote#send_sms_check', as: :send_sms_check_vote

    get '/votos/:election_id/:token', to: 'vote#election_votes_count', as: 'election_votes_count'
    get '/votos/:election_id/:election_location_id/:token', to: 'vote#election_location_votes_count', as: 'election_location_votes_count'
    match '/paper_vote/:election_id/:election_location_id/:token', to: 'vote#paper_vote', as: 'election_location_paper_vote', via: %w(get post)

    devise_for :users, controllers: {
      registrations: 'registrations',
      passwords:     'passwords',
      confirmations: 'confirmations',
      sessions:      'sessions'
    }

    get '/financiacion', to: 'page#funding', as: 'funding'
    get '/microcreditos', to: 'microcredit#index', as: 'microcredit'
    get '/microcréditos', to: redirect('/microcreditos')
    get '/microcreditos/provincias', to: 'microcredit#provinces'
    get '/microcreditos/municipios', to: 'microcredit#towns'
    get '/microcreditos/informacion', to: 'microcredit#info', as: 'microcredits_info'
    get '/microcreditos/informacion/papeletas_con_futuro', to: 'microcredit#info_mailing', as: 'microcredits_info_mailing'
    get '/microcreditos/informacion/euskera', to: 'microcredit#info_euskera', as: 'microcredits_info_euskera'
    get '/microcreditos/renovar(/:loan_id/:hash)', to: 'microcredit#renewal', as: :renewal_microcredit_loan
    get '/microcreditos/:id', to: 'microcredit#new_loan', as: :new_microcredit_loan
    get '/microcreditos/:id/detalle', to: 'microcredit#show_options', as: :show_microcredit_options_detail
    get '/microcreditos/:id/login', to: 'microcredit#login', as: :microcredit_login
    post '/microcreditos/:id', to: 'microcredit#create_loan', as: :create_microcredit_loan
    get '/microcreditos/:id/renovar(/:loan_id/:hash)', to: 'microcredit#loans_renewal', as: :loans_renewal_microcredit_loan
    post '/microcreditos/:id/renovar/:loan_id/:hash', to: 'microcredit#loans_renew', as: :loans_renew_microcredit_loan

    authenticate :user do
      scope :validator do
        scope :sms do
          get :step1, to: 'sms_validator#step1', as: 'sms_validator_step1'
          get :step2, to: 'sms_validator#step2', as: 'sms_validator_step2'
          get :step3, to: 'sms_validator#step3', as: 'sms_validator_step3'
          post :phone, to: 'sms_validator#phone', as: 'sms_validator_phone'
          post :captcha, to: 'sms_validator#captcha', as: 'sms_validator_captcha'
          post :valid, to: 'sms_validator#valid', as: 'sms_validator_valid'
        end
      end

      scope :colabora do
        delete 'baja', to: 'collaborations#destroy', as: 'destroy_collaboration'
        get 'ver', to: 'collaborations#edit', as: 'edit_collaboration'
        get '', to: 'collaborations#new', as: 'new_collaboration'
        get 'confirmar', to: 'collaborations#confirm', as: 'confirm_collaboration'
        post 'crear', to: 'collaborations#create', as: 'create_collaboration'
        post 'modificar', to: 'collaborations#modify', as: 'modify_collaboration'
        get 'puntual', to: 'collaborations#single', as: 'single_collaboration'
        get 'OK', to: 'collaborations#OK', as: 'ok_collaboration'
        get 'KO', to: 'collaborations#KO', as: 'ko_collaboration'
      end

      get 'verificacion-identidad(/:election_id)', to: 'user_verifications#new', as: 'new_user_verification'
      post 'verificacion-identidad(/:election_id)', to: 'user_verifications#create', as: 'create_user_verification'
      get 'report/(:report_code)', to: 'user_verifications#report', as: 'report_user_verification'
      get 'report_exterior/(:report_code)', to: 'user_verifications#report_exterior', as: 'report_exterior_user_verification'
      get 'report_town/(:report_code)', to: 'user_verifications#report_town', as: 'report_town_user_verification'
    end

    scope :impulsa do
      get '', to: 'impulsa#index', as: 'impulsa'
      get 'proyecto', to: 'impulsa#project', as: 'project_impulsa'
      get 'proyecto/:step', to: 'impulsa#project_step', as: 'project_step_impulsa'
      get 'evaluacion', to: 'impulsa#evaluation', as: 'evaluation_impulsa'
      post 'revisar', to: 'impulsa#review', as: 'review_impulsa'
      delete 'proyecto/borrar', to: 'impulsa#delete', as: 'delete_impulsa'
      post 'modificar', to: 'impulsa#update', as: 'update_impulsa'
      post 'modificar/:step', to: 'impulsa#update_step', as: 'update_step_impulsa'
      post 'subir/:step/:field', to: 'impulsa#upload', as: 'upload_impulsa', constraints: { field: /[^\/]*/ }
      delete 'borrar/:step/:field', to: 'impulsa#delete_file', as: 'delete_file_impulsa', constraints: { field: /[^\/]*/ }
      get 'descargar/:field', to: 'impulsa#download', as: 'download_impulsa', constraints: { field: /[^\/]*/ }

    end

    scope :brujula do
      get '', to: 'blog#index', as: 'blog'
      get ':id', to: 'blog#post', as: 'post'
      get 'categoria/:id', to: 'blog#category', as: 'category'
    end

    # http://stackoverflow.com/a/8884605/319241
    devise_scope :user do
      get '/registrations/regions/provinces', to: 'registrations#regions_provinces'
      get '/registrations/regions/municipies', to: 'registrations#regions_municipies'
      get '/registrations/vote/municipies', to: 'registrations#vote_municipies'

      authenticated :user do
        root to: 'tools#index', as: :authenticated_root
        get '/tools/militant_request', to: 'tools#militant_request', as: 'tools_militant_request'
        get 'password/new', to: 'legacy_password#new', as: 'new_legacy_password'
        post 'password/update', to: 'legacy_password#update', as: 'update_legacy_password'
        delete 'password/recover', to: 'registrations#recover_and_logout'
      end
      unauthenticated do
        root to: 'sessions#new', as: :root
      end
    end

    %w(404 422 500).each do |code|
      get code, to: 'errors#show', code: code
    end

    DynamicRouter.load
  end
  # /admin
  ActiveAdmin.routes(self)

  constraints CanAccessResque.new do

app/helpers/microcredit_helper.rb
module MicrocreditHelper
end

app/views/microcredit/_row_option.erb
<tr class="js-row ">
  <td class="<%=class_name %>"><label><%=option_name %></label></td>

  <td>
    <div style="width:<%=width %>%;color:white; background-color: <%=@colors[index%3] %> ">
      <label class="padding04"><%=number_to_currency total %></label>
    </div>
  </td>
</tr>

app/views/microcredit/_row_option_detail.erb
<tr class="js-row">
  <td><%=MicrocreditOption.find(territory_id).name %></td>
  <td><%=total %></td>
</tr>

app/views/microcredit/index.html.erb
<% content_for :title, t('microcredit.common.title', name: @brand_config["name"]) %>
<% if @brand_config["color1"] %>
  <style>
    h2 {
      color: <%=@brand_config["color1"]%> !important;
    }

    label a, p a {
      color: <%=@brand_config["color2"]%> !important;
    }

    input.button, a.button {
      background-color: <%=@brand_config["color2"]%> !important;
    }
  </style>
<% end %>
<div class="content-content">
  <h2><%= t 'microcredit.common.title', name: @brand_config["name"] %></h2>
  <p><%= t 'microcredit.common.help_us', name: @brand_config["name"] %> <%= link_to t('microcredit.common.more_info'), (@brand_config["info_link"] || microcredits_info_path), target: "_top" %></p>
  <% if @microcredits_standard.length == 0 %>
    <% if @upcoming_microcredits_standard.count > 0 %>
      <h3><%= @microcredit_index_upcoming_text %></h3>
      <p><%= t '.will_start_at', name: @brand_config["name"], hour: @upcoming_microcredits_standard.first.starts_at.strftime("%H:%M"), date: @upcoming_microcredits_standard.first.starts_at.strftime("%d/%m") %></p>
    <% elsif @finished_microcredits_standard.count > 0 %>
      <h3><%= t 'microcredit.common.has_finished' %></h3>
      <!--p><%= t('microcredit.common.campaign_results', total: number_to_euro(@finished_microcredits_standard.map {|m| m.campaign_confirmed_amount * 100}.sum, 0)).html_safe %></p -->
    <% else %>
      <h3><%= t '.no_campaigns' %></h3>
      <p><%= t '.no_campaigns_message' %></p>
    <% end %>
  <% else %>
    <div class="microcredit_boxes">
      <% @microcredits_standard.each do |m| %>
        <section class="<%= m.completed ? 'completed' : 'active' %>">
          <div>
            <% if m.remarked %>
              <p class="microcredit_box_header"><strong><%= m.title %></strong></p>
            <% else %>
            <h2><%= m.title %></h2>
            <% end %>
            <% if m.completed %>
              <%= fa_icon "check-circle" %>
              <div class="info">
                <p><strong><%= t '.success' %></strong></p>
                <p><%= t('microcredit.common.campaign_results', total: number_to_euro(m.campaign_confirmed_amount * 100, 0)).html_safe %></p>
              </div>
            <% else %>
              <div class="js-mc-graph" data-color1="<%= @brand_config['color1'] %>" data-color2="<%= @brand_config['color2'] %>">
                <div></div>
                <canvas width="90" heigth="100"></canvas>
                <div alt="<%= m.phase_counted_amount %>€" class="hide js-mc-total"><%= m.phase_counted_amount %>
                  €
                </div>
                <div alt="<%= t '.remaining' %>" class="hide js-mc-pending"><%= m.phase_limit_amount - m.phase_counted_amount %>
                  €
                </div>
              </div>
              <div class="info">
                <p>
                  <strong><%= t '.current_phase' %></strong><br/><%= number_to_euro m.phase_counted_amount * 100, 0 %>
                  / <%= number_to_euro m.phase_limit_amount * 100, 0 %>
                  <br/><strong><%= t '.accumulated' %></strong> <%= number_to_euro m.campaign_counted_amount * 100, 0 %>
                  <% if m.budget_link.present? %>
                    <br/><a href="<%= m.budget_link %>">PRESUPUESTO</a>
                  <% end %>
                </p>
                <%
                  if m.subgoals
                    remaining = m.campaign_counted_amount || 0 %>
                  <ul class='subgoals'>
                    <%
                      m.subgoals.each do |concept, subgoal| %>
                      <li><%= concept %>
                        :&nbsp;<%= number_to_euro (remaining > subgoal ? subgoal : remaining) * 100, 0 %></li>
                    <%
                      remaining -= subgoal
                      if remaining <= 0 then
                        break
                      end
                      end %></ul>
                <%
                  end %>
                <div class="buttonbox"><%= link_to t('.want_to_collaborate'), @external ? new_microcredit_loan_path(m, brand: @brand) : new_microcredit_loan_path(m), class: 'button' %>
                <% if m.microcredit_options.any? %>
                  <%= link_to "Ver desglose", @external ? show_microcredit_options_detail_path(m, brand: @brand) : show_microcredit_options_detail_path(m), class: 'microcredit_link_detail' %>
                <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </section>
      <% end %>
    </div>
  <% end %>

  <% if @microcredits_mailing.length > 0 or @upcoming_microcredits_mailing.length > 0 or @finished_microcredits_mailing.length > 0 %>
  <h2><%= t 'microcredit.mailing.title', name: @brand_config["name"]%></h2>
  <p><%= t 'microcredit.mailing.help_us', name: @brand_config["name"]%> <%= link_to t('microcredit.common.more_info'), (@brand_config["mailing_info_link"] || microcredits_info_mailing_path), target: "_top" %></p>
<% end %>

  <% if @microcredits_mailing.length == 0 %>
    <% if @upcoming_microcredits_mailing.count > 0 %>
      <h3><%= t '.will_start' %></h3>
      <p><%= t '.will_start_at', name: @brand_config["name"], hour: @upcoming_microcredits_mailing.first.starts_at.strftime("%H:%M"), date: @upcoming_microcredits_mailing.first.starts_at.strftime("%d/%m") %></p>
    <% elsif @finished_microcredits_mailing.count > 0 %>
      <h3><%= t 'microcredit.common.has_finished' %></h3>
      <p><%= t('microcredit.common.campaign_results', total: number_to_euro(@finished_microcredits_mailing.map {|m| m.campaign_confirmed_amount * 100}.sum, 0)).html_safe %></p>
    <% end %>
  <% else %>
    <div class="microcredit_boxes">
      <% @microcredits_mailing.each do |m| %>
        <section class="<%= m.completed ? 'completed' : 'active' %>">
          <div>
            <h2><%= m.title %></h2>
            <% if m.completed %>
              <%= fa_icon "check-circle" %>
              <div class="info">
                <p><strong><%= t '.success' %></strong></p>
                <p><%= t('microcredit.common.campaign_results', total: number_to_euro(m.campaign_confirmed_amount * 100, 0)).html_safe %></p>
              </div>
            <% else %>
              <div class="js-mc-graph" data-color1="<%= @brand_config['color1'] %>" data-color2="<%= @brand_config['color2'] %>">
                <div></div>
                <canvas width="90" heigth="100"></canvas>
                <div alt="<%= m.phase_counted_amount %>€" class="hide js-mc-total"><%= m.phase_counted_amount %>
                  €
                </div>
                <div alt="<%= t '.remaining' %>" class="hide js-mc-pending"><%= m.phase_limit_amount - m.phase_counted_amount %>
                  €
                </div>
              </div>
              <div class="info">
                <p>
                  <strong><%= t '.current_phase' %></strong><br/><%= number_to_euro m.phase_counted_amount * 100, 0 %>
                  / <%= number_to_euro m.phase_limit_amount * 100, 0 %>
                  <br/><strong><%= t '.accumulated' %></strong> <%= number_to_euro m.campaign_counted_amount * 100, 0 %>
                  <% if m.budget_link.present? %>
                    <br/><a href="<%= m.budget_link %>">PRESUPUESTO</a>
                  <% end %>
                </p>
                <%
                  if m.subgoals
                    remaining = m.campaign_counted_amount || 0 %>
                  <ul class='subgoals'>
                    <%
                      m.subgoals.each do |concept, subgoal| %>
                      <li><%= concept %>
                        :&nbsp;<%= number_to_euro (remaining > subgoal ? subgoal : remaining) * 100, 0 %></li>
                    <%
                      remaining -= subgoal
                      if remaining <= 0 then
                        break
                      end
                      end %></ul>
                <%
                  end %>
                <div class="buttonbox"><%= link_to t('.want_to_collaborate'), @external ? new_microcredit_loan_path(m, brand: @brand) : new_microcredit_loan_path(m), class: 'button' %></div>
              </div>
            <% end %>
          </div>
        </section>
      <% end %>
    </div>
  <% end %>
  <% if !@external %>
    <p>¿Deseas realizar una colaboración periódica o modificar la que ya
      tienes? <%= link_to "Accede a la sección de colaboraciones", new_collaboration_path %></p>
  <% end %>
</div>

app/views/microcredit/info.html.erb
<% content_for :title, "Microcréditos" %>

<div class="content-content cols microcredits-wrapper">
  <div class="row">
    <div class="col-b-4a12">
      <h2>Microcréditos Podemos</h2>
      <!--<p><%= image_tag "microcredits.jpg", alt: "Vamos a financiar la campaña con microcréditos concedidos por la gente. ¿Nos ayudas?", width: "90%" %></p>-->

      <p>Con tu ayuda queremos financiar las campañas electorales sin endeudarnos con los bancos. En Podemos somos diferentes porque funcionamos diferente.</p>
      <p><%= image_tag "microcredits2.jpg", alt: "¿Micro-qué?" %></p>
      <p>Mediante los Microcréditos ofrecemos a la ciudadanía la posibilidad de hacer un <strong>préstamo civil</strong> al Partido Político PODEMOS con vistas a sufragar los gastos electorales. Con tu ayuda queremos financiar esta campaña electoral. Puedes aportar entre 50 y 10 mil euros que te devolveremos cuando recibamos la subvención electoral correspondiente a los resultados electorales.</p>
      <p><%= image_tag "microcredits6.jpg", alt: "¿Cómo lo hago?" %></p>
      <p>Normalmente los partidos políticos sufragan sus campañas electorales de tres formas:</p>
      <ul>
        <li>Mediante anticipos de subvenciones electorales basadas en los resultados obtenidos en las elecciones del mismo tipo.</li>
        <li>Mediante créditos bancarios.</li>
        <li>Mediante fondos ordinarios del partido.</li>
      </ul>
      <p>Las subvenciones por gastos electorales se conceden una vez terminado el proceso electoral en función de los resultados obtenidos, estableciendo como límite el gasto realizado durante la campaña.</p>
      <p>De esta manera, para financiar las campañas electorales, los partidos, que por no haberse presentado anteriormente, no tienen acceso a un anticipo de la subvención que se corresponda con los resultados esperados se ven forzados a recurrir a préstamos bancarios para financiar sus campañas. Esto empuja a los partidos a un endeudamiento que puede condicionar su funcionamiento.</p>
      <p>Según el último informe del Tribunal de Cuentas (Julio de 2015), los partidos políticos españoles acumulaban una deuda total con entidades de crédito de casi 210 millones de euros. Solo entre Partido Popular y PSOE sumaban una deuda con los bancos de 120 millones. Podemos tiene una deuda con los bancos de 0 euros. No se trata de algo anecdótico: los grandes partidos españoles han estado históricamente endeudados, han asumido deudas que eran incapaces de pagar, y que luego tenían que ser condonadas o renegociadas.  Todo eso les ha privado de capacidad de acción política.</p>
      <p>La decisión de la Asamblea Ciudadana de PODEMOS de no recurrir a créditos bancarios, reflejada en el Código Ético nos lleva explorar nuevas formas de colaboración y participación económica que nos permitan sortear el diseño orientado al endeudamiento bancario que promueve el sistema de financiación de partidos.</p>

      <p>La financiación de Podemos se caracteriza por tres elementos que nos diferencian del resto de partidos:</p>
      <ul>
        <li><strong>Independencia:</strong> En Podemos no queremos depender de bancos ni de los poderes económicos y por eso nuestro objetivo ha sido ampliar al máximo la base de donantes y colaboradores.
          <!--p><%= image_tag "microcredits4.jpg", alt: "#ContigoSinBancos", align: "center", width: "90%" %></p --></li>
        <li><strong>Innovación:</strong> Para conseguir ampliar la base de donantes apostamos desde el inicio por desarrollar vías de financiación innovadoras basadas en herramientas web como el crowdfunding, los microcréditos o las colaboraciones periódicas no obligatorias.</li>
        <li><strong>Transparencia:</strong> En Podemos practicamos la transparencia que queremos ver en las instituciones. En nuestros estatutos nos comprometimos a publicar nuestras cuentas en la web.</li>
        <li>Todo el trabajo basado en estos tres principios, no solo nos ha permitido ser más austeros y eficaces en nuestras campañas si no que nos ha ayudado a ahorrar a las arcas públicas cerca de 15 millones de euros.</li>
      </ul>

      <p>Mediante los Microcréditos ofrecemos a la ciudadanía la posibilidad de hacer un <strong>préstamo civil</strong> al Partido Político PODEMOS con vistas a sufragar los gastos electorales.</p>
      <p>A tal objeto, hemos calculado la subvención por gastos electorales correspondientes a un resultado conservador que nos permitiría devolver íntegramente el importe suscrito mediante la subvención por gastos electorales.</p>
      <p>Una vez recibida <strong>la subvención</strong> para dichos gastos, ésta se aplicará <strong>de forma íntegra, directa y privilegiada a la devolución del préstamo.</strong></p>
      <p>Solo en el improbable caso de que el total de la subvención fuera menor que el total del préstamo recibido, el total de las cantidades no cubiertas deberán ser devueltas de forma proporcional en el plazo máximo de 12 meses.</p>

      <p><%= image_tag "logo.podemos-425-p.jpg", alt: "Podemos.", width: "30%" %></p>

      <div class="buttonbox">
        <%= link_to "Colaborar", microcredit_path, class: 'button' %>
      </div>
      <p><br/></p>
      <p>Si necesitas más información, envíanos tus dudas a <a href="mailto:microcreditos@podemos.info">microcreditos@podemos.info</a>.</p>
    </div>
  </div>
</div>

app/views/microcredit/loans_renewal.html.erb
<% content_for :title, t('microcredit.common.title', name: @brand_config["name"]) %>
<div class="content-content microcredits-wrapper">

<h2><%= t 'microcredit.common.title', name: @brand_config["name"]%> - <%=@microcredit.title%></h2>
<% if @renewal.nil? %>
  <p>No hemos encontrado microcréditos para renovar.</p>
<% else %>
  <p>Gracias a tu confianza y por ayudarnos a financiar nuestras campañas lejos de bancos y entidades financiera, sino de gente como tú.</p>
  <p>Para renovar tus suscripciones:<ol><li>Elige el microcrédito que deseas renovar</li><li>Acepta la extinción y renovación de la suscripción así como las condiciones del nuevo contrato para apoyar la campaña a las elecciones generales, marcando las dos casillas que aparecen a continuación.</li></ol>
  <% if @renewal.other_loans.any? %>
  <p>Además, tienes microcréditos suscritos en otras campañas que también puedes renovar: <% @renewal.other_loans.each do |loan| %>
        <%= link_to( loan.microcredit.title, loans_renewal_microcredit_loan_path(@microcredit.id, loan.id, loan.unique_hash))%>
      <%end %>.</p>
  <% end %>
  <%= errors_in_form @renewal %>
  <%= semantic_form_for @renewal, as: :renewals, url: loans_renew_microcredit_loan_path(@microcredit.id, @renewal.loan.id, @renewal.loan.unique_hash, brand: @brand), html: {method: :post, autocomplete: 'off'} do |f| %>
    <fieldset>
      <div class="inputlabel-box">
        <% if @renewal.errors.include?(:loan_renewals) %>
        <%= field_notice_box %>
        <% end %>
        <%= f.input :loan_renewals, as: :check_boxes, collection: (@renewal.recently_renewed_loans+@renewal.loans).map{|l| [ "#{l.microcredit.title} - #{number_to_euro(l.amount*100,0)}#{" (ya renovado)" if !l.renewable?}", l.id]}, disabled: @renewal.recently_renewed_loans.map(&:id), hint: "Selecciona los que deseas renovar." %>
      </div>
      <% if @renewal.loans.any? %>
        <div class="inputlabel-box">
          <% if @renewal.errors.include?(:renewal_terms) %>
              <%= field_notice_box %>
          <% end %>
          <div class="input-box">
            <%= f.check_box :renewal_terms, class: 'checkbox' %>
            <%= f.label :renewal_terms, class: 'text-xl' do %>
              <%= t '.renewal_terms_message', name: @brand_config["name"]%>
              <%= link_to t('.renewal_terms_link', name: @brand_config["name"]), @renewal.loan.microcredit.renewal_terms.url, target: "_blank"%>
            <% end %>
          </div>
        </div>

        <div class="inputlabel-box">
          <% if @renewal.errors.include?(:terms_of_service) %>
              <%= field_notice_box %>
          <% end %>
          <div class="input-box">
            <%= f.check_box :terms_of_service, class: 'checkbox' %>
            <%= f.label :terms_of_service, class: 'text-xl' do %>
              <%= t '.terms_of_service_message', name: @brand_config["name"], campaign: @microcredit.title %>
              <%= link_to t('.terms_of_service_link', name: @brand_config["name"], campaign: @microcredit.title ), @microcredit.agreement_link, target: "_blank"%>
            <% end %>
          </div>
        </div>
      <% end %>
    </fieldset>
    <% if @renewal.loans.any? %>
      <%= f.actions class: 'enter' do %>
        <%= f.action :submit, label: t(".renew"), as: :input, button_html: {class: 'button'} %>
      <% end %>
    <% end %>
  <% end %>

<% end %>
</div>