config/routes.rb
    get '/avales-candidaturas-barcelona', to: 'page#avales_barcelona', as: 'avales_barcelona'
    get '/primarias-andalucia', to: 'page#primarias_andalucia', as: 'primarias_andalucia'
    get '/listas-primarias-andaluzas', to: 'page#listas_primarias_andaluzas', as: 'listas_primarias_andaluzas'

    get '/responsables-organizacion-municipales', to: 'page#responsables_organizacion_municipales', as: 'responsables_organizacion_municipales'
    get '/responsables-municipales-andalucia', to: 'page#responsables_municipales_andalucia', as:'responsables_municipales_andalucia'
    get '/plaza-podemos-municipal', to: 'page#plaza_podemos_municipal', as:'plaza_podemos_municipal'
    get '/portal-transparencia-cc-estatal', to: 'page#portal_transparencia_cc_estatal', as:'portal_transparencia_cc_estatal'
    get '/mujer-igualdad', to: 'page#mujer_igualdad', as:"mujer_igualdad"
    get '/solicitud-consulta-ciudadana-candidatura-unidad-popular', to: 'page#alta_consulta_ciudadana', as:"alta_consulta_ciudadana"
    get '/representantes-electorales-extranjeros', to: 'page#representantes_electorales_extranjeros', as:"representantes_electorales_extranjeros"
    get '/responsables-areas-cc-autonomicos', to: 'page#responsables_areas_cc_autonomicos', as:"responsables_areas_cc_autonomicos"
    get '/boletin-correo-electronico', to: 'page#boletin_correo_electronico', as:"boletin_correo_electronico"
    get '/responsable-web-autonomico', to: 'page#responsable_web_autonomico', as: 'responsable_web_autonomico'

    get '/comparte-el-cambio/compartir-casa', to: 'page#offer_hospitality', as: 'offer_hospitality'
    get '/comparte-el-cambio/encuentra-casa', to: 'page#find_hospitality', as: 'find_hospitality'
    get '/comparte-el-cambio/compartir-coche-sevilla', to: 'page#share_car_sevilla', as: 'share_car_sevilla'
    get '/comparte-el-cambio/encuentra-viaje-sevilla', to: 'page#find_car_sevilla', as: 'find_car_sevilla'
    get '/comparte-el-cambio/compartir-coche-doshermanas', to: 'page#share_car_doshermanas', as: 'share_car_doshermanas'
    get '/comparte-el-cambio/encuentra-viaje-doshermanas', to: 'page#find_car_doshermanas', as: 'find_car_doshermanas'
    get '/comparte-el-cambio/valoracion-propietarios', to: 'page#comparte_cambio_valoracion_propietarios', as: 'comparte_cambio_valoracion_propietarios'
    get '/comparte-el-cambio/valoracion-usuarios', to: 'page#comparte_cambio_valoracion_usuarios', as: 'comparte_cambio_valoracion_usuarios'

    get '/apoderados-campana-autonomica-andalucia', to: 'page#apoderados_campana_autonomica_andalucia', as: 'apoderados_campana_autonomica_andalucia'
    get '/candidaturas-primarias-autonomicas', to: 'page#candidaturas_primarias_autonomicas', as: 'candidaturas_primarias_autonomicas'
    get '/listas-primarias-autonomicas', to: 'page#listas_primarias_autonomicas', as: 'listas_primarias_autonomicas'
    get '/avales-candidaturas-primarias', to: 'page#avales_candidaturas_primarias', as: 'avales_candidaturas_primarias'
    get '/iniciativa-ciudadana', to: 'page#iniciativa_ciudadana', as: 'iniciativa_ciudadana'

    get '/cuentas-consejos-autonomicos-33', to: 'page#cuentas_consejos_autonomicos', as: 'cuentas_consejos_autonomicos'
    get '/condiciones-uso-correo-34', to: 'page#condiciones_uso_correo', as: 'condiciones_uso_correo'

    get '/propuestas', to: 'proposals#index', as: 'proposals'
    get '/propuestas/info', to: 'proposals#info', as: 'proposals_info'
    get '/propuestas/:id', to: 'proposals#show', as: 'proposal'
    post '/apoyar/:proposal_id', to: 'supports#create', as: 'proposal_supports'

    get :notices, to: 'notice#index', as: 'notices'
    get '/vote/create/:election_id', to: 'vote#create', as: :create_vote
    get '/vote/create_token/:election_id', to: 'vote#create_token', as: :create_token_vote
    get '/vote/check/:election_id', to: 'vote#check', as: :check_vote

    get '/vote/sms_check/:election_id', to: 'vote#sms_check', as: :sms_check_vote
    get '/vote/send_sms_check/:election_id', to: 'vote#send_sms_check', as: :send_sms_check_vote

    get '/votos/:election_id/:token', to: 'vote#election_votes_count', as: 'election_votes_count'
    get '/votos/:election_id/:election_location_id/:token', to: 'vote#election_location_votes_count', as: 'election_location_votes_count'
    match '/paper_vote/:election_id/:election_location_id/:token', to: 'vote#paper_vote', as: 'election_location_paper_vote', via: %w(get post)

    devise_for :users, controllers: {
      registrations: 'registrations',
      passwords:     'passwords',
      confirmations: 'confirmations',
      sessions:      'sessions'
    }

    get '/financiacion', to: 'page#funding', as: 'funding'
    get '/microcreditos', to: 'microcredit#index', as: 'microcredit'
    get '/microcréditos', to: redirect('/microcreditos')
    get '/microcreditos/provincias', to: 'microcredit#provinces'
    get '/microcreditos/municipios', to: 'microcredit#towns'
    get '/microcreditos/informacion', to: 'microcredit#info', as: 'microcredits_info'
    get '/microcreditos/informacion/papeletas_con_futuro', to: 'microcredit#info_mailing', as: 'microcredits_info_mailing'
    get '/microcreditos/informacion/euskera', to: 'microcredit#info_euskera', as: 'microcredits_info_euskera'
    get '/microcreditos/renovar(/:loan_id/:hash)', to: 'microcredit#renewal', as: :renewal_microcredit_loan
    get '/microcreditos/:id', to: 'microcredit#new_loan', as: :new_microcredit_loan
    get '/microcreditos/:id/detalle', to: 'microcredit#show_options', as: :show_microcredit_options_detail
    get '/microcreditos/:id/login', to: 'microcredit#login', as: :microcredit_login
    post '/microcreditos/:id', to: 'microcredit#create_loan', as: :create_microcredit_loan
    get '/microcreditos/:id/renovar(/:loan_id/:hash)', to: 'microcredit#loans_renewal', as: :loans_renewal_microcredit_loan
    post '/microcreditos/:id/renovar/:loan_id/:hash', to: 'microcredit#loans_renew', as: :loans_renew_microcredit_loan

    authenticate :user do
      scope :validator do
        scope :sms do
          get :step1, to: 'sms_validator#step1', as: 'sms_validator_step1'
          get :step2, to: 'sms_validator#step2', as: 'sms_validator_step2'
          get :step3, to: 'sms_validator#step3', as: 'sms_validator_step3'
          post :phone, to: 'sms_validator#phone', as: 'sms_validator_phone'
          post :captcha, to: 'sms_validator#captcha', as: 'sms_validator_captcha'
          post :valid, to: 'sms_validator#valid', as: 'sms_validator_valid'
        end
      end

      scope :colabora do
        delete 'baja', to: 'collaborations#destroy', as: 'destroy_collaboration'
        get 'ver', to: 'collaborations#edit', as: 'edit_collaboration'
        get '', to: 'collaborations#new', as: 'new_collaboration'
        get 'confirmar', to: 'collaborations#confirm', as: 'confirm_collaboration'
        post 'crear', to: 'collaborations#create', as: 'create_collaboration'
        post 'modificar', to: 'collaborations#modify', as: 'modify_collaboration'
        get 'puntual', to: 'collaborations#single', as: 'single_collaboration'
        get 'OK', to: 'collaborations#OK', as: 'ok_collaboration'
        get 'KO', to: 'collaborations#KO', as: 'ko_collaboration'
      end

      get 'verificacion-identidad(/:election_id)', to: 'user_verifications#new', as: 'new_user_verification'
      post 'verificacion-identidad(/:election_id)', to: 'user_verifications#create', as: 'create_user_verification'
      get 'report/(:report_code)', to: 'user_verifications#report', as: 'report_user_verification'
      get 'report_exterior/(:report_code)', to: 'user_verifications#report_exterior', as: 'report_exterior_user_verification'
      get 'report_town/(:report_code)', to: 'user_verifications#report_town', as: 'report_town_user_verification'
    end

    scope :impulsa do
      get '', to: 'impulsa#index', as: 'impulsa'
      get 'proyecto', to: 'impulsa#project', as: 'project_impulsa'
      get 'proyecto/:step', to: 'impulsa#project_step', as: 'project_step_impulsa'
      get 'evaluacion', to: 'impulsa#evaluation', as: 'evaluation_impulsa'
      post 'revisar', to: 'impulsa#review', as: 'review_impulsa'
      delete 'proyecto/borrar', to: 'impulsa#delete', as: 'delete_impulsa'
      post 'modificar', to: 'impulsa#update', as: 'update_impulsa'
      post 'modificar/:step', to: 'impulsa#update_step', as: 'update_step_impulsa'
      post 'subir/:step/:field', to: 'impulsa#upload', as: 'upload_impulsa', constraints: { field: /[^\/]*/ }
      delete 'borrar/:step/:field', to: 'impulsa#delete_file', as: 'delete_file_impulsa', constraints: { field: /[^\/]*/ }
      get 'descargar/:field', to: 'impulsa#download', as: 'download_impulsa', constraints: { field: /[^\/]*/ }

    end

    scope :brujula do
      get '', to: 'blog#index', as: 'blog'
      get ':id', to: 'blog#post', as: 'post'
      get 'categoria/:id', to: 'blog#category', as: 'category'
    end

    # http://stackoverflow.com/a/8884605/319241
    devise_scope :user do
      get '/registrations/regions/provinces', to: 'registrations#regions_provinces'
      get '/registrations/regions/municipies', to: 'registrations#regions_municipies'
      get '/registrations/vote/municipies', to: 'registrations#vote_municipies'

      authenticated :user do
        root to: 'tools#index', as: :authenticated_root
        get '/tools/militant_request', to: 'tools#militant_request', as: 'tools_militant_request'
        get 'password/new', to: 'legacy_password#new', as: 'new_legacy_password'
        post 'password/update', to: 'legacy_password#update', as: 'update_legacy_password'
        delete 'password/recover', to: 'registrations#recover_and_logout'
      end
      unauthenticated do
        root to: 'sessions#new', as: :root
      end
    end

    %w(404 422 500).each do |code|
      get code, to: 'errors#show', code: code
    end

    DynamicRouter.load
  end
  # /admin
  ActiveAdmin.routes(self)

  constraints CanAccessResque.new do

app/controllers/impulsa_controller.rb
class ImpulsaController < ApplicationController
  before_action :authenticate_user!, except: [ :index ]
  before_action :set_variables
  before_action :check_project, except: [ :index ]
 
  def index
    @upcoming = ImpulsaEdition.upcoming.first if @edition.nil?
  end

  def project
  end

  def evaluation
  end

  def project_step
    @show_errors = @project.wizard_status[@step][:filled]
    @project.valid? & @project.wizard_step_valid? if @show_errors
  end

  def update
    redirect_to project_impulsa_path and return unless @project.editable?
    if @project.save
      redirect_to project_step_impulsa_path(step: @project.wizard_step) 
    else
      render :project
    end
  end

  def review
    if @project.mark_for_review
      flash[:notice] = "El proyecto ha sido marcado para ser revisado."
    else
      flash[:error] = "El proyecto no puede ser marcado para ser revisado."
    end
    redirect_to project_impulsa_path
  end

  def delete
    if @project.deleteable?
      if @project.destroy
        flash[:notice] = "El proyecto ha sido borrado."
        redirect_to impulsa_path
      else
        flash[:error] = "El proyecto no ha podido ser borrado."
        redirect_to project_impulsa_path
      end
    else
      if @project.mark_as_resigned
        flash[:notice] = "Tu renuncia a realizar el proyecto ha sido registrada."
      else
        flash[:error] = "No se ha podido registrar la renuncia al proyecto."
      end
      redirect_to project_impulsa_path
    end
  end

  def update_step
    redirect_to project_impulsa_path and return unless @project.saveable?

    changes = (@project.changes.keys-["wizard_step"]).any?

    if @project.save
      if @project.wizard_step_errors.any?
        redirect_to project_step_impulsa_path(step: @project.wizard_step)
      elsif @project.wizard_next_step
        redirect_to project_step_impulsa_path(step: @project.wizard_next_step)
      else
        redirect_to project_impulsa_path
      end
      return
    end
    render :edit
  end

  def upload
    gname, fname = params[:field].split(".")
    result = @project.assign_wizard_value(gname, fname, params[:file])
    errors = [
            case result
              when :wrong_extension
                "El tipo de fichero subido no es correcto."
              when :wrong_size
                "El tamaño del fichero subido supera el límite permitido."
              when :wrong_field
                "El fichero subido no corresponde a ningún campo. Por favor, recarga la página e intenta subirlo nuevamente."
            end 
          ]

    if errors.any?
      render json: errors, status: :unprocessable_entity
    else
      @project.save
      filename = @project.wizard_values[params[:field]]
      ret = {
              name: filename,
              path: download_impulsa_path(field: filename)
            }
      render json: ret
    end
  end

  def delete_file
    gname, fname = params[:field].split(".")
    result = @project.assign_wizard_value(gname, fname, nil)
    errors = [
            case result
              when :wrong_field
                "El fichero indicado no corresponde a ningún campo. Por favor, recarga la página e intenta borrarlo nuevamente."
            end 
          ]

    if errors.any?
      render json: errors, status: :unprocessable_entity
    else
      @project.save
      render json: {}
    end
  end

  def download
    gname, fname, extension = params[:field].split(".")
    send_file @project.wizard_path(gname, fname)
  end

private
  def set_variables
    @edition = ImpulsaEdition.current
    return if @edition.nil? || !current_user

    @step = params[:step]
    @project = @edition.impulsa_projects.where(user:current_user).first
    if @project.nil? && @edition.allow_creation?
      @project = ImpulsaProject.new user: current_user
    end

    @available_categories = @edition.impulsa_edition_categories
    @available_categories = @available_categories.non_authors if !current_user.impulsa_author?

    if @project.present? then
      @project.wizard_step = @step if @step
      @project.assign_attributes(project_params) unless params[:impulsa_project].blank?
    end
  end

  def project_params
    if !@project.persisted?
      params.require(:impulsa_project).permit(:name, :impulsa_edition_category_id)
    elsif @step.blank?
      if @project.editable? then params.require(:impulsa_project).permit(:name) else {} end
    else
      params.require(:impulsa_project).permit(*@project.wizard_step_params)
    end
  end

  def check_project
    redirect_to impulsa_path if @project.nil?
  end

end

app/helpers/impulsa_helper.rb
module ImpulsaHelper

  def filetypes_to_file_filter filetype
    (ImpulsaProject::FILETYPES[filetype.to_sym].map { |ext| ".#{ext}" } + 
      ImpulsaProject::FILETYPES[filetype.to_sym].map { |ext| ImpulsaProject::EXTENSIONS[ext] } 
    ).join(",") if filetype
  end
end

app/views/impulsa/_field.html.erb
<%
  key = "#{gname}.#{fname}"
  field_name = :"_wiz_#{gname}__#{fname}"
  value = project.send(field_name) # TO-DO: this force to call missing_method, Formtastic use don't work with arrays (check_boxes) 
  disable = !project.wizard_editable_field?(gname, fname)
  hint = field[:tip].present? ? fa_icon("asterisk", text: raw(field[:tip])) : content_tag(:span)
%>

<div class="inputlabel-box impulsa">
  <% if field[:type]=="file" %>
    <%= f.input field_name, label: field[:title], as: :file, hint: hint, input_html: {class: 'input-xl', accept: filetypes_to_file_filter(field[:filetype]), "data-url"=>upload_impulsa_path(step: step, field: key), disabled: disable} if !disable%>
    <div class="file form-group file-data">
      <span class="form-label">
        <% if disable %>
          <%= f.label field[:title], class:"control-label" %>
        <% else %>
          <label class="template"><%= link_to(fa_icon("cloud-download", text: t("podemos.impulsa.model_link")), field[:template]) if field[:template] %></label>
        <% end %>
      </span>

      <span class="form-wrapper">
        <div class="progress hidden"><div class="progress-bar progress-bar-success"></div></div>
        <div class="current-file<%=" hidden" if project.wizard_values[key].blank?%>"> <%= link_to(project.wizard_values[key] || "", download_impulsa_path(field: project.wizard_values[key] || ""), class: :download)%> <%= link_to(fa_icon("trash"), delete_file_impulsa_path(step: step, field: key), method: :delete, "data-remote"=>true, "data-confirm"=>"Esto borrará el fichero. ¿Deseas continuar?", class: :delete) if !disable%></div>
      </span>
    </div>
  <% elsif field[:type].in? ["select", "check_boxes"] %>
    <%= f.input field_name, label: field[:title], as: field[:type], hint: hint, collection: field[:collection].to_a.map(&:reverse), input_html: {disabled: disable, class: if field[:type]=="check_boxes" then '' else 'input-xl' end} %>
  <% elsif field[:type]=="boolean" %>
      <%= f.label field[:title], for: field_name %>
      <div class="input-box">
        <label class="choice"><%= f.check_box field_name, class: 'checkbox', disabled: disable %><%= field[:tip] %></label>
      </div>
  <% else %>
    <%= f.input field_name, label: field[:title], as: field[:type], hint: hint, input_html: {class: 'input-xl', disabled: disable} %>
  <% end %>
</div>

app/views/impulsa/_steps.html.erb
<nav class="steps vertical-steps">
  <ul>
    <li class="main<%= ' active' if "main"==step %>">
      <a href="<%=project_impulsa_path%>">Proyecto</a>
    </li>
    <% if project.validated? || project.invalidated? %>
      <li class="main<%= ' active' if "evaluation"==step %>">
        <a href="<%=evaluation_impulsa_path%>">Evaluación</a>
      </li>
    <% end %>
    <% project.wizard_status.each do |sname, info| %>
      <li class="<%= if info[:filled] then if info[:errors]==0 then "is-ok" else "is-not-ok" end else "" end %><%= ' active' if sname==step %>">
        <a href="<%=project_step_impulsa_path(step: sname)%>"><%= info[:title] %><%= content_tag(:span, class: "errors") { info[:errors].to_s } if info[:filled] && info[:errors]>0 && info[:fields]>0 %></a>
      </li>
    <% end if project.persisted? %>
  </ul>
</nav>

app/views/impulsa/inactive.html.erb
<% content_for :title, t("podemos.impulsa.title") %>

<div class="content-content cols">
  <div class="row">
    <div class="col-b-4a12">
      <%= content_tag(:h2, t("podemos.impulsa.title")) %>
      <% if @upcoming %>
        <%= content_tag(:p, t("podemos.impulsa.upcoming", start_at: @upcoming.start_at.strftime("%d de %m"))) %>
      <% else %>
        <%= content_tag(:p, t("podemos.impulsa.noupcoming")) %>
      <% end %>
    </div>
  </div>
</div>

app/views/impulsa/project.html.erb
<% content_for :title, t("podemos.impulsa.title") %>


<div class="content-content cols impulsa">
  <div class="row">
    <div class="col-b-4a12">
      <%= render partial: "steps", locals: {project: @project, step: 'main'} %>
      <div class="data-form-container">
        <% if @project.name.present? %>
          <%= content_tag(:h2, @project.name)%>
        <% else %>
          <%= content_tag(:h2, "Nuevo proyecto de IMPULSA") %>
        <% end %>

        <% case @project.state 
            when "new", "spam" %>
            <% if @edition.allow_creation? %>
              <% if @project.persisted? %>
                <p>Ya tienes creado un proyecto para la edición actual del Programa IMPULSA. <% if @project.wizard_has_errors? %>Debes completar todos los datos del proyecto para que podamos revisarlo. Una vez que lo hayas hecho debes volver a está página para marcar tu proyecto para revisión.<% else %>Para que podamos revisar que todos los datos enviados son correctos debes presionar el botón "marcar para revisión".<%end%></p>
              <% else %>
                <p>Estás a punto de comenzar a inscribir un proyecto para la edición actual del Programa IMPULSA. Antes de comenzar te recomendamos que consultes las <a href="http://impulsa.podemos.info/#bases">bases de esta edición</a>. Lee atentamente el apartado de la documentación que hay que entregar.</p>
              <% end %>
             <p>Recuerda que la fecha límite para presentar tu proyecto es el <strong><%= l((@edition.new_projects_until-1.second).to_date, format: :long) %></strong>.</p>
            <% else %>
              <p>No hemos recibido, en plazo, toda la información necesaria sobre el proyecto que has presentado a esta edición de IMPULSA. El plazo de presentación de proyectos ha finalizado, por lo que lamentamos comunicarte que tu proyecto no podrá ser revisado.</p>
            <% end %>
          <% when "fixes" %>
            <% if @project.fixable? %>
              <p>Hemos revisado el proyecto que has presentado a IMPULSA y hemos detectado algunos puntos que necesitan subsanación. <% if @project.wizard_has_errors? %>Por favor, revisa los pasos marcados con números, lee atentamente nuestras indicaciones y corrígelos. Una vez que lo hayas hecho debes volver a esta página para marcar tu proyecto para que sea revisado nuevamente.<% else %>Para que podamos revisar nuevamente tu proyecto debes presionar el botón <strong><%=t("podemos.impulsa.mark_for_review")%></strong>.<%end%></p>
              <p>Recuerda que la fecha límite para que los datos de tu proyecto estén subsanados es el <strong><%= l((@edition.review_projects_until-1.second).to_date, format: :long) %></strong>.</p>
            <% else %>
              <p>No hemos recibido, en plazo, la subsanación de los errores indicados en el proyecto que has presentado a esta edición de IMPULSA. El plazo de subsanación ha finalizado, por lo que lamentamos comunicarte que tu proyecto no pasa a la fase de validación.</p>
            <% end %>
          <% when "review" %>
            <p>Hemos recibido tu proyecto y estamos revisando que todos los datos sean correctos. En cuanto terminemos este proceso te avisaremos por correo electrónico, hasta que eso suceda puedes seguir modificando tu proyecto si lo deseas. Te recomendamos que estés atento para poder corregirlo si fuera necesario, ya que todos los datos deberán estar subsanados antes del <strong><%= l((@edition.review_projects_until-1.second).to_date, format: :long) %></strong> para que pueda ser evaluado. </p>
          <% when "review_fixes" %>
            <p>Hemos recibido tu proyecto y estamos revisando que todos los datos sean correctos. En cuanto terminemos este proceso te avisaremos por correo electrónico, hasta que eso suceda puedes seguir modificando tu proyecto si lo deseas. Te recomendamos que estés atento para poder corregirlo si fuera necesario, ya que todos los datos deberán estar subsanados antes del <strong><%= l((@edition.review_projects_until-1.second).to_date, format: :long) %></strong> para que pueda ser evaluado. </p>
          <% when "validable" %>
            <p>Hemos recibido correctamente el proyecto que has presentado, está completo y pasa a la fase de evaluación. Esto se realizará antes del <strong><%= l((@edition.validation_projects_until-1.second).to_date, format: :long) %></strong>.</p>
          <% when "invalidated" %>
            <p>Lamentamos comunicarte que el proyecto que has presentado a la edición actual de IMPULSA no ha superado la fase de evaluación. Puedes consultar el resultado detallado de la evaluación <%=link_to("aquí", evaluation_impulsa_path)%>.</p>
          <% when "validated" %>
            <p>Una vez realizada la evaluación de los proyectos presentados a la edición actual de IMPULSA, tenemos el placer de informarte de que <strong>tu proyecto ha sido validado</strong>. Puedes consultar el resultado detallado de la evaluación <%=link_to("aquí", evaluation_impulsa_path)%>.</p>
          <% when "discarded" %>
          <% when "resigned" %>
            <p>Lamentamos que hayas renunciado a realizar tu proyecto y te animamos a presentarlo en la próxima edición de IMPULSA.</p>
          <% when "winner" %>
        <% end %>
        <p>Si tienes cualquier consulta, escribe a <a href='mailto:<%=@edition.email%>'><%=@edition.email%></a> y te responderemos en el menor tiempo posible. También puedes consultar las <a href="http://impulsa.podemos.info/#bases">bases de esta edición</a>.</p>
      
        <h3>Datos del proyecto</h3>
        <%= errors_in_form @project %>

        <%= semantic_form_for @project, url: update_impulsa_path, html: { method: :post, autocomplete: 'off'} do |f| %>
          <fieldset>
            <div class="inputlabel-box">
              <% if @project.errors.include?(:impulsa_edition_category) %>
              <%= field_notice_box %>
              <% end %>
              <%= f.input :impulsa_edition_category, as: :select, collection: @available_categories.sort_by(&:name), required: true, input_html: {class: 'input-xl', onchange: @project.persisted? ? "submit()" : "", disabled: @project.persisted? } %>
              <%= content_tag(:p, fa_icon("asterisk", text: "Selecciona cuidadosamente esta opción, ya que no podrás cambiarla luego", class: "fa-fw"), class: :note) if !@project.persisted? %>
            </div>
            <div class="inputlabel-box">
              <% if @project.errors.include?(:name) %>
              <%= field_notice_box %>
              <% end %>
              <%= f.input :name, required: true, input_html: { class: 'input-xl', disabled: !@project.editable?} %>
            </div>
          </fieldset>

          <% if !@project.persisted? %>
            <fieldset>
              <div class="inputlabel-box">
                <% if @project.errors.include?(:terms_of_service) %>
                    <%= field_notice_box %>
                <% end %>

                <%= f.label :terms_of_service %>
                <div class="input-box">
                  <%= f.check_box :terms_of_service, required: true, class: 'checkbox' %>
                  <p class="text-xl"><%= t("podemos.impulsa.terms_of_service", link: "http://impulsa.podemos.info/#bases").html_safe %></p>
                </div>
              </div>
              <div class="inputlabel-box">
                <% if @project.errors.include?(:data_truthfulness) %>
                    <%= field_notice_box %>
                <% end %>

                <%= f.label :data_truthfulness %>
                <div class="input-box">
                  <%= f.check_box :data_truthfulness, required: true, class: 'checkbox' %>
                  <p class="text-xl"><%= t("podemos.impulsa.data_truthfulness") %></p>
                </div>
              </div>
              <div class="inputlabel-box">
                <% if @project.errors.include?(:content_rights) %>
                    <%= field_notice_box %>
                <% end %>

                <%= f.label :content_rights %>
                <div class="input-box">
                  <%= f.check_box :content_rights, required: true, class: 'checkbox' %>
                  <p class="text-xl"><%= t("podemos.impulsa.content_rights") %></p>
                </div>
              </div>
            </fieldset>
          <% end %>
          <%= f.actions do %>
            <%= link_to(t("podemos.impulsa.mark_for_review"), review_impulsa_path, class: 'button button-success', method: :post) if @project.markable_for_review? %>
            <%= f.action :submit, label: "Guardar", :as => :input, button_html: {class: 'button'} if @project.editable?%>
            <%= link_to("Borrar proyecto", delete_impulsa_path, "data-confirm"=>"Esto borrará el proyecto y no se podrá recuperar. ¿Deseas continuar?", class: 'button button-danger', method: :delete) if @project.persisted? && @project.deleteable? %>
            <%= link_to("Renunciar al proyecto", delete_impulsa_path, "data-confirm"=>"El proyecto será descartado y ya no podrás presentar otro. ¿Deseas continuar?", class: 'button button-danger', method: :delete) if @project.persisted? && !@project.deleteable? && !@project.resigned? %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>